### ISSUE TITLE
still using Ubuntu

### ISSUE THREAD

**Issue by martin2250** [Quizznor/dotfiles#1]
you should use arch

**Comment by umute97** [comment]
+1

**Comment by umute97** [comment]
@martin2250 +1

**Comment by Quizznor** [comment]
Fixed in [db727c4](https://github.com/Quizznor/dotfiles).

/cc @umute97 @martin2250

**Comment by martin2250** [comment]
![image](https://user-images.githubusercontent.com/8293473/63641806-9f44a600-c6b4-11e9-989d-3c06021c0db9.png)

doesn't work, please fix

**Comment by Quizznor** [comment]
Have you tried turning it off and on again?

**Comment by martin2250** [comment]
Yeah, though involuntarily... my PC crashed while it was suspended when I turned on a fan on the other side of the room :neutral_face: 
pls fix

**Comment by umute97** [comment]
@martin2250 Able to reproduce on my system. Rebooting doesn't fix. :/

**Comment by Quizznor** [comment]
Do the rooms that your machines are located in happen to have windows?

**Comment by martin2250** [comment]
Yeah, six of them

**Comment by Quizznor** [comment]
I'm afraid there's your issue. I wrote this program specifically for arch linux. It will not run under windows.

Try moving your machine to a different room.

**Comment by martin2250** [comment]
Just tried it with my laptop in the windowless basement... still doesn't work. Maybe my kernel is too old?
```
$uname -r
5.2.9-arch1-1-ARCH
```

**Comment by Quizznor** [comment]
Please report back with your results. I'm eager to get to the bottom of this issue

**Comment by umute97** [comment]
Anything new on this issue yet? Starting to think the dev isn't taking this issue seriously enough... /disappointment

**Comment by martin2250** [comment]
No luck, still getting the same error message

**Comment by Quizznor** [comment]
No. You're lying

**Comment by martin2250** [comment]
What makes you think that?

**Comment by Quizznor** [comment]
@umute97 told me.

**Comment by martin2250** [comment]
@umute97 why did you do that?

@Quizznor just to get to the bottom of this, can you provide a little information about your install? What's your `uname -a`?

**Comment by umute97** [comment]
@Quizznor is lying. You told him that.

**Comment by Quizznor** [comment]
I'm afraid I cannot give you that information, seeing as it's been classified by the CIA via §12,2 : Hiob.

**Comment by martin2250** [comment]
Something makes me think that you wrote `arch.exe` for Ubuntu and didn't actually switch to archlinux

**Comment by Quizznor** [comment]
What makes you think that?

**Comment by martin2250** [comment]
@umute97 told me.

**Comment by Quizznor** [comment]
@umute97 why did you do that?

@martin2250  just to get to the bottom of this, can you provide a little information about your install? What's your uname -a?

**Comment by umute97** [comment]
Yes, I did. But only to cover up sensitive CIA documents.

**Comment by martin2250** [comment]
![image](https://user-images.githubusercontent.com/8293473/63642539-f9e3ff00-c6c0-11e9-8272-a558bb6f8a0b.png)
you're in luck, my `uname -a` was recently declassified

**Comment by Quizznor** [comment]
Wait. You're already running arch? You will not need arch.exe then. 

This conversation has been a huge waste of time.

**Comment by martin2250** [comment]
Well, telling people 'I use arch btw' got boring, so I'm always looking for more elaborate ways to accomplish the task.

I use arch btw.

**Comment by martin2250** [comment]
You should still provide instructions on how to run this program on arch.

**Comment by martin2250** [comment]
and actually switch to arch

**Comment by Quizznor** [comment]
> You should still provide instructions on how to run this program on arch.

I advise you to take a look at the source code. Perhaps you can get it running on your machine then.
